### PR TITLE
Allow per-part default shape to be configured

### PR DESCRIPTION
**Pull request by siimav**
The current default of a 4x4m rectangular slab doesn't make much sense IMO. I would like to configure it to look like a smaller fin in RO.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
This seems to be conflicting with the merge did of your other PR, can you please fix, I don't want to mess it up

**Comment by siimav** [comment]
Rebased to resolve the conflicts.

**Comment by linuxgurugamer** [comment]
I was testing this, the save as default didn't seem to be working , or possibly I'm not using it correctly.  I attached a part, changed some of the sizes and then clicked the "Save as default" button at the bottom of the window

**Comment by siimav** [comment]
Oof, you appear to be correct that this change broke the "Save as default" feature. Looks like it was overwriting the values in the static fields that I now made non-static so that they could be MM-patched. So previously the overwritten defaults were active for the lifetime of the current game session and got reset on next startup.

I need to figure out if we want to restore this exact behavior or make them persist between game sessions. 🤔

**Comment by linuxgurugamer** [comment]
From what I can tell from the PR, the following are the fields which you removed the "static" setting from:

sharedBaseLengthDefaults
sharedBaseWidthRootDefaults
sharedBaseWidthTipDefaults
sharedBaseOffsetRootDefaults
sharedBaseOffsetTipDefaults
sharedBaseThicknessRootDefaults
sharedBaseThicknessTipDefaults
sharedEdgeTypeLeadingDefaults
sharedEdgeWidthLeadingRootDefaults
sharedEdgeWidthLeadingTipDefaults
sharedEdgeTypeTrailingDefaults
sharedEdgeWidthTrailingRootDefaults
sharedEdgeWidthTrailingTipDefaults

I am going to revert this change, and then add some code to load the values into these fields from a config file (if exists), that should give you the ability to have different defaults using a MM config file.  I'll also include a cfg file so it will always be there

**Comment by siimav** [comment]
> I am going to revert this change, and then add some code to load the values into these fields from a config file (if exists), that should give you the ability to have different defaults using a MM config file. I'll also include a cfg file so it will always be there

I guess that would work assuming that the "Save as default" feature doesn't try to overwrite the cfg (and thus invalidate the MM cache). My initial idea was that you could use MM to clone the part into different copies that all come with a different predefined shape. I agree that this gets awkward in the presence of "Save as default" since all the parts would turn out to be the exact same. So your idea is probably the better way forward.

**Comment by siimav** [comment]
Implemented the changes in #24

**Pull request merged**
